version: '3.6'
services:
  ubuntu:
    image: ubuntu:22.04
    command: /bin/bash -c "apt update && apt install iperf -y && iperf -i 60 -c 192.168.100.170 --port 5003 && /bin/bash"
    deploy:
      restart_policy:
        condition: any
      mode: global



